name: ci build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bazel build
      run: bazel build ...
    - name: bazel test
      run: bazel test test:unittest
