name: ci build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile-witm-bazel:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - name: bazel build
      run: bazel build ...
    - name: bazel test
      run: bazel test test:unittest
